// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// Runtime Version:4.0.30319.42000
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using Microsoft.VisualBasic;
using Microsoft.VisualBasic.CompilerServices;

namespace exams
{
    [System.Runtime.CompilerServices.CompilerGenerated()]
    [System.CodeDom.Compiler.GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.0.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
    internal sealed partial class Settings : System.Configuration.ApplicationSettingsBase
    {
        private static Settings defaultInstance = (Settings)Synchronized(new Settings());

        #region My.Settings Auto-Save Functionality
        /* TODO ERROR: Skipped IfDirectiveTrivia
        #If _MyType = "WindowsForms" Then
        */
        private static bool addedHandler;
        private static object addedHandlerLockObject = new object();

        [DebuggerNonUserCode()]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        private static void AutoSaveSettings(object sender, EventArgs e)
        {
            if (My.MyProject.Application.SaveMySettingsOnExit)
            {
                My.MySettingsProperty.Settings.Save();
            }
        }
        /* TODO ERROR: Skipped EndIfDirectiveTrivia
        #End If
        */
        #endregion

        public static Settings Default
        {
            get
            {

                /* TODO ERROR: Skipped IfDirectiveTrivia
                #If _MyType = "WindowsForms" Then
                */
                if (!addedHandler)
                {
                    lock (addedHandlerLockObject)
                    {
                        if (!addedHandler)
                        {
                            My.MyProject.Application.Shutdown += AutoSaveSettings;
                            addedHandler = true;
                        }
                    }
                }
                /* TODO ERROR: Skipped EndIfDirectiveTrivia
                #End If
                */
                return defaultInstance;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("localhost")]
        public string host
        {
            get
            {
                return Conversions.ToString(this["host"]);
            }

            set
            {
                this["host"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("root")]
        public string userName
        {
            get
            {
                return Conversions.ToString(this["userName"]);
            }

            set
            {
                this["userName"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("ADMIN1234")]
        public string passWord
        {
            get
            {
                return Conversions.ToString(this["passWord"]);
            }

            set
            {
                this["passWord"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("schoolss")]
        public string dbName
        {
            get
            {
                return Conversions.ToString(this["dbName"]);
            }

            set
            {
                this["dbName"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("10")]
        public float fontSize
        {
            get
            {
                return Conversions.ToSingle(this["fontSize"]);
            }

            set
            {
                this["fontSize"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("Segoe UI Symbol")]
        public string userFont
        {
            get
            {
                return Conversions.ToString(this["userFont"]);
            }

            set
            {
                this["userFont"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("Caramel")]
        public string selectedTheme
        {
            get
            {
                return Conversions.ToString(this["selectedTheme"]);
            }

            set
            {
                this["selectedTheme"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("0")]
        public int users
        {
            get
            {
                return Conversions.ToInteger(this["users"]);
            }

            set
            {
                this["users"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("7474")]
        public string dPport
        {
            get
            {
                return Conversions.ToString(this["dPport"]);
            }

            set
            {
                this["dPport"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("DemoDatabase")]
        public string defaultDb
        {
            get
            {
                return Conversions.ToString(this["defaultDb"]);
            }

            set
            {
                this["defaultDb"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("")]
        public string API
        {
            get
            {
                return Conversions.ToString(this["API"]);
            }

            set
            {
                this["API"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("")]
        public string APIUserName
        {
            get
            {
                return Conversions.ToString(this["APIUserName"]);
            }

            set
            {
                this["APIUserName"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("")]
        public string Sender
        {
            get
            {
                return Conversions.ToString(this["Sender"]);
            }

            set
            {
                this["Sender"] = value;
            }
        }
    }

    namespace My
    {
        [HideModuleName()]
        [DebuggerNonUserCode()]
        [System.Runtime.CompilerServices.CompilerGenerated()]
        internal static class MySettingsProperty
        {
            [System.ComponentModel.Design.HelpKeyword("My.Settings")]
            internal static Settings Settings
            {
                get
                {
                    return Settings.Default;
                }
            }
        }
    }
}